version: "3.9"  # optional since v1.27.0
services:
  # Golang 1.15
  golang:
    container_name: golang
    image: golang:1.18.0-stretch
    ports:
    - "3000:3000"
    restart : always
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    tty: true
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      TZ: "Asia/Jakarta"
      MYSQL_ROOT_PASSWORD: "root"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
  mongo:
    container_name: mongo
    image: mongo:5.0.6-focal
    restart : always
    ports : 
    - "27018:27017"
  elastic:
    container_name: elastic
    image: elasticsearch:6.8.21
    ports :
      - "9500:9200"
